// <auto-generated />
using System;
using HW43;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW43.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW43.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Client1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Client2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Client3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Client4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Client5"
                        });
                });

            modelBuilder.Entity("HW43.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("DateOfBirht")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HiredData")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("TitleId");

                    b.ToTable("Employe", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirht = new DateTime(1560, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Josh",
                            HiredData = new DateTime(2009, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pipka",
                            OfficeId = 1,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirht = new DateTime(1450, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vasan",
                            HiredData = new DateTime(1850, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zapal",
                            OfficeId = 2,
                            TitleId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirht = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nina",
                            HiredData = new DateTime(2000, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ponos",
                            OfficeId = 3,
                            TitleId = 3
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirht = new DateTime(2, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maksim",
                            HiredData = new DateTime(2020, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Katz",
                            OfficeId = 4,
                            TitleId = 4
                        },
                        new
                        {
                            EmployeeId = 5,
                            DateOfBirht = new DateTime(1476, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Valera",
                            HiredData = new DateTime(2003, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ponosov",
                            OfficeId = 5,
                            TitleId = 5
                        });
                });

            modelBuilder.Entity("HW43.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeProjectId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartedData")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeProject", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeProjectId = 1,
                            EmployeeId = 1,
                            ProjectId = 1,
                            Rate = 2500m,
                            StartedData = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 2,
                            EmployeeId = 2,
                            ProjectId = 2,
                            Rate = 6200m,
                            StartedData = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 3,
                            EmployeeId = 3,
                            ProjectId = 3,
                            Rate = 7630m,
                            StartedData = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 4,
                            EmployeeId = 4,
                            ProjectId = 4,
                            Rate = 8463m,
                            StartedData = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeProjectId = 5,
                            EmployeeId = 5,
                            ProjectId = 5,
                            Rate = 84320m,
                            StartedData = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HW43.Office", b =>
                {
                    b.Property<int>("OfficeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OfficeID");

                    b.ToTable("Office", (string)null);

                    b.HasData(
                        new
                        {
                            OfficeID = 1,
                            Location = "USA",
                            Title = "Some Title"
                        },
                        new
                        {
                            OfficeID = 2,
                            Location = "Canada",
                            Title = "Some Title2"
                        },
                        new
                        {
                            OfficeID = 3,
                            Location = "Japan",
                            Title = "Some Title3"
                        },
                        new
                        {
                            OfficeID = 4,
                            Location = "Africa",
                            Title = "Some Title4"
                        },
                        new
                        {
                            OfficeID = 5,
                            Location = "UK",
                            Title = "Some Title5"
                        });
                });

            modelBuilder.Entity("HW43.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedData")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.ToTable("Project", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budget = 12000m,
                            ClientId = 1,
                            Name = "Fanta",
                            StartedData = new DateTime(2020, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 2,
                            Budget = 24000m,
                            ClientId = 2,
                            Name = "CSGO",
                            StartedData = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 3,
                            Budget = 850000m,
                            ClientId = 3,
                            Name = "WOW",
                            StartedData = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 4,
                            Budget = 8520000m,
                            ClientId = 4,
                            Name = "Wurm",
                            StartedData = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectId = 5,
                            Budget = 8150000m,
                            ClientId = 5,
                            Name = "RDR2",
                            StartedData = new DateTime(2017, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HW43.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TitleId");

                    b.ToTable("Title", (string)null);

                    b.HasData(
                        new
                        {
                            TitleId = 1,
                            Name = "Title1a"
                        },
                        new
                        {
                            TitleId = 2,
                            Name = "Title2"
                        },
                        new
                        {
                            TitleId = 3,
                            Name = "Title3"
                        },
                        new
                        {
                            TitleId = 4,
                            Name = "Title4a"
                        },
                        new
                        {
                            TitleId = 5,
                            Name = "Title5"
                        });
                });

            modelBuilder.Entity("HW43.Employee", b =>
                {
                    b.HasOne("HW43.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HW43.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("HW43.EmployeeProject", b =>
                {
                    b.HasOne("HW43.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HW43.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HW43.Project", b =>
                {
                    b.HasOne("HW43.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
